import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
  admin,
  provider,
}: Readonly<{
  children: React.ReactNode;
  admin: React.ReactNode;
  provider: React.ReactNode;
}>) {
  return (
    <>
      {admin}
      {provider}
      {children}
    </>
  );
}
