import { AppSidebar } from "@/components/layout/app-sidebar";
import { SiteHeader } from "@/components/layout/site-header";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
  admin,
  provider,
}: Readonly<{
  children: React.ReactNode;
  admin: React.ReactNode;
  provider: React.ReactNode;
}>) {
  const user = { role: "admin" };
  return (
    <>
      <SidebarProvider>
        <AppSidebar variant="inset" />
        <SidebarInset>
          <SiteHeader />
          <div className="md:p-6 p-5">
            {user?.role === "admin" ? admin : provider}
            {children}
          </div>
        </SidebarInset>
      </SidebarProvider>
    </>
  );
}
