import { AppSidebar } from "@/components/layout/app-sidebar";
import { SiteHeader } from "@/components/layout/site-header";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { ROLE } from "@/lib/roles";
import { UserService } from "@/services/user.service";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const userService = new UserService();
export default async function DashboardLayout({
  children,
  admin,
  provider,
}: Readonly<{
  children: React.ReactNode;
  admin: React.ReactNode;
  provider: React.ReactNode;
}>) {
  const user = await userService.currentUser();
  return (
    <>
      <SidebarProvider>
        <AppSidebar variant="inset" />
        <SidebarInset>
          <SiteHeader />
          <div className="md:p-6 p-5">
            {user?.data?.role === ROLE.ADMIN ? admin : provider}
            {children}
          </div>
        </SidebarInset>
      </SidebarProvider>
    </>
  );
}
