import Cart from "@/components/shared/cart/Cart";
import CustomCursor from "@/components/shared/cursor/CustomCursor";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function CommonLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      {/* <CustomCursor /> */}
      <div className="fixed bottom-10 right-10 z-100">
        <Cart />
      </div>
      {children}
    </>
  );
}
